spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/search-house?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  # redis config
  redis:
    database: 0
    host: 132.232.33.80
    password: root@redis
    port: 6379
    pool:
      min-idle: 1
    timeout: 3000

  #thymeleaf
  thymeleaf:
    cache: false

  #图片上传配置
  http:
    multipart:
      enabled: true
      location: /tmp/search-house/images/
      file-size-threshold: 5MB
      max-file-size: 20MB


#数据库日志
logging:
  level:
    org:
      hibernate:
        SQL: debug
